In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Airbnb_Open_Data.csv")
data.head()

C:\Users\tubac\AppData\Local\Temp\ipykernel_14920\1113942449.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Airbnb_Open_Data.csv")

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [3]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [5]:
data["license"]

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
102594    NaN
102595    NaN
102596    NaN
102597    NaN
102598    NaN
Name: license, Length: 102599, dtype: object

---
* Deleting redundant columns.
* Renaming the columns.
* Dropping duplicates.
* Remove the NaN values from the dataset
* Cleaning individual columns.
* Check for some more Transformations
---

In [7]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [8]:
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
'country code', 'instant_bookable', 'cancellation_policy', 'room type',
'Construction year', 'price', 'service fee', 'minimum nights',
'number of reviews', 'last review']
columns_to_drop = ['reviews per month',
'review rate number', 'calculated host listings count',
'availability 365', 'house_rules', 'license', 'id']

In [9]:
len(columns_to_keep)

19

In [10]:
len(columns_to_drop)

7

# 1st Method, Filtering Data

In [12]:
df = data[columns_to_keep]
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

# 2nd Method, Dropping Columns

In [14]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [15]:
data.drop(columns = columns_to_drop, inplace = True)

In [16]:
data.shape

(102599, 19)

## Renaming the columns

In [18]:
data.rename(columns = {"NAME":"Name"}, inplace = True)

In [19]:
data.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [20]:
new_column_names = []

for i in data.columns:
    new_column_names.append(i.upper())

In [21]:
new_column_names

['NAME',
 'HOST ID',
 'HOST_IDENTITY_VERIFIED',
 'HOST NAME',
 'NEIGHBOURHOOD GROUP',
 'NEIGHBOURHOOD',
 'LAT',
 'LONG',
 'COUNTRY',
 'COUNTRY CODE',
 'INSTANT_BOOKABLE',
 'CANCELLATION_POLICY',
 'ROOM TYPE',
 'CONSTRUCTION YEAR',
 'PRICE',
 'SERVICE FEE',
 'MINIMUM NIGHTS',
 'NUMBER OF REVIEWS',
 'LAST REVIEW']

In [22]:
new_dataframe_to_modify = data.copy()

In [23]:
new_dataframe_to_modify.columns = new_column_names

In [24]:
new_dataframe_to_modify.columns

Index(['NAME', 'HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME',
       'NEIGHBOURHOOD GROUP', 'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY',
       'COUNTRY CODE', 'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE',
       'CONSTRUCTION YEAR', 'PRICE', 'SERVICE FEE', 'MINIMUM NIGHTS',
       'NUMBER OF REVIEWS', 'LAST REVIEW'],
      dtype='object')

## Dropping duplicates

In [26]:
data.duplicated().sum()

541

In [27]:
data.drop_duplicates(inplace = True)

In [28]:
data.duplicated().sum()

0

## Remove the NaN values from the dataset

In [30]:
data.isna().sum()

Name                        250
host id                       0
host_identity_verified      289
host name                   404
neighbourhood group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country code                131
instant_bookable            105
cancellation_policy          76
room type                     0
Construction year           214
price                       247
service fee                 273
minimum nights              400
number of reviews           183
last review               15832
dtype: int64

In [31]:
data.dropna(inplace = True)

In [32]:
data.isna().sum()

Name                      0
host id                   0
host_identity_verified    0
host name                 0
neighbourhood group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country code              0
instant_bookable          0
cancellation_policy       0
room type                 0
Construction year         0
price                     0
service fee               0
minimum nights            0
number of reviews         0
last review               0
dtype: int64

## Cleaning individual columns

In [34]:
data["host_identity_verified"].str.upper()

0         UNCONFIRMED
1            VERIFIED
4            VERIFIED
5            VERIFIED
7         UNCONFIRMED
             ...
102029    UNCONFIRMED
102030       VERIFIED
102031       VERIFIED
102032    UNCONFIRMED
102040       VERIFIED
Name: host_identity_verified, Length: 83969, dtype: object

In [35]:
data["host_identity_verified"] = data["host_identity_verified"].str.upper()

In [142]:
data["host_identity_verified"].unique()

array(['UNCONFIRMED', 'VERIFIED'], dtype=object)

In [144]:
data["host_identity_verified"] = data["host_identity_verified"].map({"UNCONFIRMED": 0, "VERIFIED": 1})

In [146]:
data["host_identity_verified"]

0        0
1        1
2        1
3        1
4        0
        ..
83964    0
83965    1
83966    1
83967    0
83968    1
Name: host_identity_verified, Length: 83969, dtype: int64

In [150]:
data["host_identity_verified"].value_counts()

host_identity_verified
0    42010
1    41959
Name: count, dtype: int64

In [148]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,NaN,Private room,2020.0,966,193,10.0,9.0,2021-10-19
1,1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,NaN,Entire home/apt,2007.0,142,28,30.0,45.0,2022-05-21
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,NaN,Entire home/apt,2009.0,204,41,10.0,9.0,2018-11-19
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,NaN,Entire home/apt,2013.0,577,115,3.0,74.0,2019-06-22
4,7,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,NaN,Private room,2009.0,1060,212,45.0,49.0,2017-10-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,102029,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,NaN,Private room,2018.0,822,164,1.0,9.0,2019-04-25
83965,102030,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,NaN,Private room,2015.0,455,91,4.0,36.0,2018-06-27
83966,102031,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,NaN,Private room,2020.0,1078,216,1.0,58.0,2019-06-10
83967,102032,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,NaN,Private room,2007.0,103,21,7.0,40.0,2019-06-23
83968,102040,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,NaN,Private room,2022.0,982,196,1.0,239.0,2019-06-29

In [140]:
# data["instant_bookable"] = data["instant_bookable"].map({"t": 1, "f": 0})

In [37]:
data["instant_bookable"].apply(lambda x: 1 if x == True else 0)

0         0
1         0
4         0
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: instant_bookable, Length: 83969, dtype: int64

In [38]:
data["instant_bookable"] = data["instant_bookable"].apply(lambda x: 1 if x == True else 0)

In [39]:
data.reset_index(inplace = True)

In [40]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0,4/25/2019
83965,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0,6/27/2018
83966,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0,6/10/2019
83967,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0,6/23/2019
83968,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0,6/29/2019

In [41]:
data["price"].head(3)

0    $966
1    $142
2    $204
Name: price, dtype: object

In [42]:
data["price"] = data["price"].str.replace("$", "")

In [43]:
data["price"]

0          966
1          142
2          204
3          577
4        1,060
          ...
83964      822
83965      455
83966    1,078
83967      103
83968      982
Name: price, Length: 83969, dtype: object

In [44]:
data["price"] = data["price"].str.replace(",", "")

In [45]:
data["price"]

0         966
1         142
2         204
3         577
4        1060
         ...
83964     822
83965     455
83966    1078
83967     103
83968     982
Name: price, Length: 83969, dtype: object

In [46]:
data["price"][15]

'370 '

In [47]:
data["price"] = data["price"].str.replace(" ", "")

In [48]:
data["price"][15]

'370'

In [49]:
data["price"]

0         966
1         142
2         204
3         577
4        1060
         ...
83964     822
83965     455
83966    1078
83967     103
83968     982
Name: price, Length: 83969, dtype: object

In [50]:
data["price"].astype(int)

0         966
1         142
2         204
3         577
4        1060
         ...
83964     822
83965     455
83966    1078
83967     103
83968     982
Name: price, Length: 83969, dtype: int32

In [51]:
type(data["price"][1])

str

In [52]:
type(data["price"].astype(int)[1])

numpy.int32

In [53]:
data["price"] = data["price"].astype(int)

In [54]:
type(data["price"][1])

numpy.int32

In [55]:
data["service fee"] = data["service fee"].str.replace("$", "")

In [56]:
data["service fee"]

0        193
1         28
2         41
3        115
4        212
         ...
83964    164
83965     91
83966    216
83967     21
83968    196
Name: service fee, Length: 83969, dtype: object

In [57]:
data["service fee"] = data["service fee"].astype(int)

In [58]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,193,10.0,9.0,10/19/2021
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,28,30.0,45.0,5/21/2022
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,41,10.0,9.0,11/19/2018
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,115,3.0,74.0,6/22/2019
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,212,45.0,49.0,10/5/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,164,1.0,9.0,4/25/2019
83965,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,91,4.0,36.0,6/27/2018
83966,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,216,1.0,58.0,6/10/2019
83967,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,21,7.0,40.0,6/23/2019
83968,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,196,1.0,239.0,6/29/2019

In [59]:
data["last review"]

0        10/19/2021
1         5/21/2022
2        11/19/2018
3         6/22/2019
4         10/5/2017
            ...
83964     4/25/2019
83965     6/27/2018
83966     6/10/2019
83967     6/23/2019
83968     6/29/2019
Name: last review, Length: 83969, dtype: object

In [60]:
data["last review"] = pd.to_datetime(data["last review"])

In [120]:
data["last review"]

0       2021-10-19
1       2022-05-21
2       2018-11-19
3       2019-06-22
4       2017-10-05
           ...
83964   2019-04-25
83965   2018-06-27
83966   2019-06-10
83967   2019-06-23
83968   2019-06-29
Name: last review, Length: 83969, dtype: datetime64[ns]

In [122]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,193,10.0,9.0,2021-10-19
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,28,30.0,45.0,2022-05-21
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,41,10.0,9.0,2018-11-19
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,115,3.0,74.0,2019-06-22
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,212,45.0,49.0,2017-10-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,164,1.0,9.0,2019-04-25
83965,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,91,4.0,36.0,2018-06-27
83966,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,216,1.0,58.0,2019-06-10
83967,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,21,7.0,40.0,2019-06-23
83968,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,196,1.0,239.0,2019-06-29

In [124]:
data["cancellation_policy"]

0          strict
1        moderate
2        moderate
3        flexible
4        moderate
           ...
83964    flexible
83965    moderate
83966    flexible
83967    moderate
83968      strict
Name: cancellation_policy, Length: 83969, dtype: object

In [134]:
order = {"strict": 2, "moderate": 1, "flexible": 0}
data["cancellation_policy"] = data["cancellation_policy"].map(order)

In [136]:
data["cancellation_policy"]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
83964   NaN
83965   NaN
83966   NaN
83967   NaN
83968   NaN
Name: cancellation_policy, Length: 83969, dtype: float64

In [138]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,NaN,Private room,2020.0,966,193,10.0,9.0,2021-10-19
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,NaN,Entire home/apt,2007.0,142,28,30.0,45.0,2022-05-21
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,NaN,Entire home/apt,2009.0,204,41,10.0,9.0,2018-11-19
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,NaN,Entire home/apt,2013.0,577,115,3.0,74.0,2019-06-22
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,NaN,Private room,2009.0,1060,212,45.0,49.0,2017-10-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,NaN,Private room,2018.0,822,164,1.0,9.0,2019-04-25
83965,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,NaN,Private room,2015.0,455,91,4.0,36.0,2018-06-27
83966,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,NaN,Private room,2020.0,1078,216,1.0,58.0,2019-06-10
83967,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,NaN,Private room,2007.0,103,21,7.0,40.0,2019-06-23
83968,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,NaN,Private room,2022.0,982,196,1.0,239.0,2019-06-29

In [160]:
from datetime import datetime

current_year = datetime.now().year
current_year

2025

In [162]:
data["Building Age"] = current_year - data["Construction year"]

In [164]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,Building Age
0,0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,0,NaN,Private room,2020.0,966,193,10.0,9.0,2021-10-19,5.0
1,1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,0,NaN,Entire home/apt,2007.0,142,28,30.0,45.0,2022-05-21,18.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,0,NaN,Entire home/apt,2009.0,204,41,10.0,9.0,2018-11-19,16.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,1,NaN,Entire home/apt,2013.0,577,115,3.0,74.0,2019-06-22,12.0
4,7,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,0,NaN,Private room,2009.0,1060,212,45.0,49.0,2017-10-05,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,102029,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,...,0,NaN,Private room,2018.0,822,164,1.0,9.0,2019-04-25,7.0
83965,102030,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,...,1,NaN,Private room,2015.0,455,91,4.0,36.0,2018-06-27,10.0
83966,102031,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,...,1,NaN,Private room,2020.0,1078,216,1.0,58.0,2019-06-10,5.0
83967,102032,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,...,0,NaN,Private room,2007.0,103,21,7.0,40.0,2019-06-23,18.0
83968,102040,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,...,1,NaN,Private room,2022.0,982,196,1.0,239.0,2019-06-29,3.0

In [166]:
data["Building Age"].describe()

count    83969.000000
mean        12.512439
std          5.761698
min          3.000000
25%          8.000000
50%         13.000000
75%         18.000000
max         22.000000
Name: Building Age, dtype: float64

In [182]:
# Create a new column 'Age Category' by binning the 'Building Age' values

data["Age Category"] = pd.cut(
    data["Building Age"], # The numerical column to be categorized
    bins = [0,10,30,50],  # Define age intervals: 0â€“10, 10â€“30, 30â€“50
    labels = ["new", "moderate", "old"] # Labels for each age group
)

In [184]:
data["Age Category"]

0             new
1        moderate
2        moderate
3        moderate
4        moderate
           ...
83964         new
83965         new
83966         new
83967    moderate
83968         new
Name: Age Category, Length: 83969, dtype: category
Categories (3, object): ['new' < 'moderate' < 'old']

In [185]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,Building Age,Age Category
0,0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,NaN,Private room,2020.0,966,193,10.0,9.0,2021-10-19,5.0,new
1,1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,NaN,Entire home/apt,2007.0,142,28,30.0,45.0,2022-05-21,18.0,moderate
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,NaN,Entire home/apt,2009.0,204,41,10.0,9.0,2018-11-19,16.0,moderate
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,NaN,Entire home/apt,2013.0,577,115,3.0,74.0,2019-06-22,12.0,moderate
4,7,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,NaN,Private room,2009.0,1060,212,45.0,49.0,2017-10-05,16.0,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,102029,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,...,NaN,Private room,2018.0,822,164,1.0,9.0,2019-04-25,7.0,new
83965,102030,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,...,NaN,Private room,2015.0,455,91,4.0,36.0,2018-06-27,10.0,new
83966,102031,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,...,NaN,Private room,2020.0,1078,216,1.0,58.0,2019-06-10,5.0,new
83967,102032,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,...,NaN,Private room,2007.0,103,21,7.0,40.0,2019-06-23,18.0,moderate
83968,102040,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,...,NaN,Private room,2022.0,982,196,1.0,239.0,2019-06-29,3.0,new

In [188]:
data.to_csv("cleaned_data.csv")

In [190]:
pd.read_csv("cleaned_data.csv")

,Unnamed: 0,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,...,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,Building Age,Age Category
0,0,0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,NaN,Private room,2020.0,966,193,10.0,9.0,2021-10-19,5.0,new
1,1,1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,NaN,Entire home/apt,2007.0,142,28,30.0,45.0,2022-05-21,18.0,moderate
2,2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,NaN,Entire home/apt,2009.0,204,41,10.0,9.0,2018-11-19,16.0,moderate
3,3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,...,NaN,Entire home/apt,2013.0,577,115,3.0,74.0,2019-06-22,12.0,moderate
4,4,7,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,...,NaN,Private room,2009.0,1060,212,45.0,49.0,2017-10-05,16.0,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,83964,102029,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,...,NaN,Private room,2018.0,822,164,1.0,9.0,2019-04-25,7.0,new
83965,83965,102030,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,...,NaN,Private room,2015.0,455,91,4.0,36.0,2018-06-27,10.0,new
83966,83966,102031,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,...,NaN,Private room,2020.0,1078,216,1.0,58.0,2019-06-10,5.0,new
83967,83967,102032,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,...,NaN,Private room,2007.0,103,21,7.0,40.0,2019-06-23,18.0,moderate
83968,83968,102040,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,...,NaN,Private room,2022.0,982,196,1.0,239.0,2019-06-29,3.0,new

In [198]:
data.drop(columns = ["index"], inplace = True)

In [205]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,...,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,Building Age,Age Category
0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,...,NaN,Private room,2020.0,966,193,10.0,9.0,2021-10-19,5.0,new
1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,...,NaN,Entire home/apt,2007.0,142,28,30.0,45.0,2022-05-21,18.0,moderate
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,...,NaN,Entire home/apt,2009.0,204,41,10.0,9.0,2018-11-19,16.0,moderate
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,...,NaN,Entire home/apt,2013.0,577,115,3.0,74.0,2019-06-22,12.0,moderate
4,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,...,NaN,Private room,2009.0,1060,212,45.0,49.0,2017-10-05,16.0,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,...,NaN,Private room,2018.0,822,164,1.0,9.0,2019-04-25,7.0,new
83965,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,...,NaN,Private room,2015.0,455,91,4.0,36.0,2018-06-27,10.0,new
83966,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,...,NaN,Private room,2020.0,1078,216,1.0,58.0,2019-06-10,5.0,new
83967,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,...,NaN,Private room,2007.0,103,21,7.0,40.0,2019-06-23,18.0,moderate
83968,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,...,NaN,Private room,2022.0,982,196,1.0,239.0,2019-06-29,3.0,new

In [200]:
data.to_csv("cleaned_data_without_index.csv", index = False)

In [202]:
pd.read_csv("cleaned_data_without_index.csv")

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,...,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,Building Age,Age Category
0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,...,NaN,Private room,2020.0,966,193,10.0,9.0,2021-10-19,5.0,new
1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,...,NaN,Entire home/apt,2007.0,142,28,30.0,45.0,2022-05-21,18.0,moderate
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,...,NaN,Entire home/apt,2009.0,204,41,10.0,9.0,2018-11-19,16.0,moderate
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,...,NaN,Entire home/apt,2013.0,577,115,3.0,74.0,2019-06-22,12.0,moderate
4,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,...,NaN,Private room,2009.0,1060,212,45.0,49.0,2017-10-05,16.0,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,...,NaN,Private room,2018.0,822,164,1.0,9.0,2019-04-25,7.0,new
83965,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,...,NaN,Private room,2015.0,455,91,4.0,36.0,2018-06-27,10.0,new
83966,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,...,NaN,Private room,2020.0,1078,216,1.0,58.0,2019-06-10,5.0,new
83967,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,...,NaN,Private room,2007.0,103,21,7.0,40.0,2019-06-23,18.0,moderate
83968,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,...,NaN,Private room,2022.0,982,196,1.0,239.0,2019-06-29,3.0,new

In [207]:
data.to_excel("excel_cleaned_data.xlsx")

In [209]:
data.to_excel("excel_cleaned_data_index_false.xlsx", index = False)

In [210]:
pd.read_excel("excel_cleaned_data.xlsx")

,Unnamed: 0,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,Building Age,Age Category
0,0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,NaN,Private room,2020,966,193,10,9,2021-10-19,5,new
1,1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,NaN,Entire home/apt,2007,142,28,30,45,2022-05-21,18,moderate
2,2,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,NaN,Entire home/apt,2009,204,41,10,9,2018-11-19,16,moderate
3,3,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,NaN,Entire home/apt,2013,577,115,3,74,2019-06-22,12,moderate
4,4,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,NaN,Private room,2009,1060,212,45,49,2017-10-05,16,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,83964,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,...,NaN,Private room,2018,822,164,1,9,2019-04-25,7,new
83965,83965,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,...,NaN,Private room,2015,455,91,4,36,2018-06-27,10,new
83966,83966,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,...,NaN,Private room,2020,1078,216,1,58,2019-06-10,5,new
83967,83967,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,...,NaN,Private room,2007,103,21,7,40,2019-06-23,18,moderate
83968,83968,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,...,NaN,Private room,2022,982,196,1,239,2019-06-29,3,new

In [212]:
pd.read_excel("excel_cleaned_data_index_false.xlsx")

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,...,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,Building Age,Age Category
0,Clean & quiet apt home by the park,80014485718,0,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,...,NaN,Private room,2020,966,193,10,9,2021-10-19,5,new
1,Skylit Midtown Castle,52335172823,1,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,...,NaN,Entire home/apt,2007,142,28,30,45,2022-05-21,18,moderate
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,1,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,...,NaN,Entire home/apt,2009,204,41,10,9,2018-11-19,16,moderate
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,1,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,...,NaN,Entire home/apt,2013,577,115,3,74,2019-06-22,12,moderate
4,BlissArtsSpace!,90821839709,0,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,...,NaN,Private room,2009,1060,212,45,49,2017-10-05,16,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,Cozy room in a 2B with backyard access,5155155913,0,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,...,NaN,Private room,2018,822,164,1,9,2019-04-25,7,new
83965,An East Williamsburg Delight,71564706996,1,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,...,NaN,Private room,2015,455,91,4,36,2018-06-27,10,new
83966,Cozy bedroom in williamsburg,83101851929,1,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,...,NaN,Private room,2020,1078,216,1,58,2019-06-10,5,new
83967,Spacious Room w/ 2 Bed,69037598918,0,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,...,NaN,Private room,2007,103,21,7,40,2019-06-23,18,moderate
83968,"Room in Queens, NY, near LGA.",56457739998,1,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,...,NaN,Private room,2022,982,196,1,239,2019-06-29,3,new